title: <p align="center"> Satya Dintakurthy </p>
logo: /assets/img/Satyam.png

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="www.linkedin.com/in/satyanarayana-dintakurthy-dataprofessional/">LinkedIn</a> |
  <a href="https://dtsatyam.github.io/Portfolio/">GitHub</a>
  
  <br>   
  I am an enthusiastic Data Professional with 14+ years of experience in Data Management.
  6+ years of experience working as Lead Data Scientist & ML Developer.
  Currently spearheading as Chief Manager with ICICI Bank, Bangalore, India.
  <br>
  </p>



theme: jekyll-theme-minimal
