title: <p align="center"> Satyanarayana Dintakurthy </p>
logo: /assets/img/Satya.png

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="www.linkedin.com/in/satyanarayana-dintakurthy-dataprofessional/">LinkedIn</a> |
  <a href="https://dtsatyam.github.io/Portfolio/">GitHub</a>
  
  <br>   
  I am an enthusiastic Self-directed Data Professional with 14+ years of experience in Data Management projects.
  Having 6+ years of experience working as Lead Data Scientist & Machine Learning Developer.
  Currently spearheading as Chief Manager with ICICI Bank, Bangalore, India.
  <br>
  </p>



theme: jekyll-theme-minimal
